name: Remaining PR
on:
  schedule:
  - cron: '0 7 * * *'  # 매일 04:00 UTC (한국 시간 13:00)
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements.txt

      - name: run remainingPR.py
        run: |
          python .github/remainingPR.py